# Generated by Django 5.0 on 2024-01-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='car',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.car'),
            preserve_default=False,
        ),
    ]
