# Generated by Django 5.0 on 2024-01-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_service_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='car',
            name='mods',
            field=models.ManyToManyField(to='main_app.mod'),
        ),
    ]
